### ISSUE TITLE
Bug: Errors in test lack context

### ISSUE THREAD

**Issue by xakdog** [teamkeel/keel#1371]
## Problem

Errors in tests provide little to no context. Here's an example

<img width="889" alt="image" src="https://github.com/teamkeel/keel/assets/17473315/72fec5d8-52d7-411d-9597-9c5f97b88ef4">

## How to reproduce

Generate a default project and add `tests/main.test.ts` file

```ts
import { expect, test } from 'vitest';
import { actions, models } from '@teamkeel/testing';
 
test('a problematic test', async () => {
  const johnDoe = await models.identity.create({
    id: 'john', // <-- this is the problem
    email: 'john@example.com',
  });

  const project = await models.project.create({
    title: 'Rust Doge',
    ownerId: johnDoe.id,
  });

  const fetchedRecord = await actions.withIdentity(johnDoe).getProject({ id: project.id });

  expect(fetchedRecord).toEqual(project);
});
```

**Comment by davenewza** [comment]
The underlying issue here is that we recently added support for setting a custom, non-KSUID, value for the `id` column, and clearly this was missed during development.  I've put together a fix and tests for this issue here #1373.  Great find and thank you for reporting it.

Typically a `ERR_INTERNAL` should never happen in production.  It means "something went very wrong".  I've approved #1372 to help us with troubleshooting these issues.
